#!/bin/sh

# X11 library.

. "$HOME/.local/lib/variables"

# Get a list of monitors.
monitors() {
	xrandr --listmonitors | tail -n +2 | while read -r line; do
		echo "${line##* }"
	done
}

# Turn off a monitor.
monioff() {
	xrandr --output "$1" --off
}

# Set the background image to $1.
setbg() {
	hsetroot -tile "$1"
}

# Set the Xft DPI
setdpi() {
	xrdb -merge <<EOF
Xft.dpi: 120

Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb
EOF
}

# Initializes the Xresources
setupxrdb() {
	# Figure out the theme
	theme="$(cat "$WSJ_CONF_DIR/theme")"
	if [ -z "$theme" ]; then
		# Assume gruvbox-dark
		theme="gruvbox-dark"
	fi

	xrdb -merge < "$WSJ_DATA_DIR/$theme.Xresources"
	xrdb -merge < "$HOME/.Xresources"

	unset theme
}

# Grab a Xresources value
getxrdb() {
	# Figure out the theme
	theme="$(cat "$WSJ_CONF_DIR/theme")"
	if [ -z "$theme" ]; then
		# Assume gruvbox-dark
		theme="gruvbox-dark"
	fi

	if [ -z "$DISPLAY" ]; then
		# Xrdb not running
		cat "$WSJ_CONF_DIR/$theme.Xresources" "$HOME/.Xresources" | xrdb -n -get "$1"
	else
		xrdb -n -get "$1"
	fi
}
